config/routes.rb
Rails.application.routes.draw do
  root 'surveys#index'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :creators, only: [:new, :create, :show, :edit, :update]

  resources :surveys do

    get 'statistic', on: :member

    resources :answers, only: [:new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :questions, only: [:new, :create, :edit, :update, :destroy] do
      resources :question_choices, only: [:index, :new, :create, :edit, :update, :destroy]
    end

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question_choice.rb
class QuestionChoice < ApplicationRecord
  has_many :question_choice_questions
  has_many :questions, through: :question_choice_questions, dependent: :destroy
  has_one :answer, dependent: :destroy
 
  validates :choice,
    length: { maximum: 140 }

  def self.find_or_init(params, creator)
    question_choice = QuestionChoice.joins(questions: :surveys).where("creator_id = #{creator.id}").find_by(choice: params[:choice])
    if question_choice.blank?
      # create a new record
      question_choice = QuestionChoice.new(choice: params[:choice])
    else
      # return the record
      return question_choice
    end
  end
end

app/controllers/question_choices_controller.rb
class QuestionChoicesController < ApplicationController
  before_action :logged_in_creator, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :get_survey_question, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :correct_creator, only: [:index, :new, :edit, :update, :destroy]

  def index
    @question_choices = @question.question_choices
  end

  def new
    @question_choice = @question.question_choices.new
  end

  def create
    @question_choice = QuestionChoice.find_or_init(question_choice_params, current_creator)

    if @question_choice.new_record?
      unless @question_choice.save
        flash[:danger] = "Qualcosa è andato storto :/"
      end
    end
    @question_choice.questions << Question.find(params[:question_id])
    redirect_to survey_question_question_choices_path(@survey, @question)
  end

  def edit
    @question_choice = QuestionChoice.find(params[:id])
  end

  def update
    @question_choice = QuestionChoice.find(params[:id])
    unless @question_choice.update(question_choice_params)
      flash[:danger] = "Qualcosa è andato storto :/"
    end
    redirect_to survey_question_question_choices_path(@survey, @question)
  end

  def destroy
    @question_choice = QuestionChoice.find(params[:id])
    unless @question_choice.questions.destroy(@question)
      flash[:danger] = "Qualcosa è andato storto :/"
    end
    redirect_to survey_question_question_choices_path(@survey, @question)
  end


  private

  def question_choice_params
    params.require(:question_choice).permit(:choice)
  end

  def get_survey_question
    @survey = Survey.find(params[:survey_id])
    @question = Question.find(params[:question_id])
  end

  def correct_creator
    redirect_to(root_url) if current_creator != @survey.creator
  end
end

app/helpers/question_choices_helper.rb
module QuestionChoicesHelper
  def question_choice_suggested
    # Query used for autocomplete 
    QuestionChoice.order(:choice).joins(questions: :surveys).where("creator_id=?", current_creator.id).map(&:choice)
  end
end

app/views/question_choices/edit.html.erb
<%= render 'shared/header_survey' %>
<small class="mb-3"> <%= link_to "← Torna indietro", survey_path(@survey) %> </small>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <div class="card-text">

        <h5 class="mb-4">Modifica la domanda</h5>

        <%= form_with model: @question_choice, url: survey_question_question_choice_path(@survey, @question, @question_choice) do |f| %>
          <div class="form-group px-3">
            <%= f.text_field :choice, class: "form-control", required: true,
                data: { autocomplete_choice: question_choice_suggested } %>
          </div>
          <%= f.submit "Modifica", class:"btn btn-primary mt-3",
                data: { confirm: "Confermi di voler modificare questa risposta? Tutte le risposte con questo nome da te create verranno modificate." } %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/question_choices/index.html.erb
<%= render 'shared/header_survey' %>
<small class="mb-3"> <%= link_to "← Torna indietro", survey_path(@survey) %> </small>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <div class="card-text">

        <h5 class="mb-0">Possibili risposte</h5>
        <small class="text-muted">
          Tipo risposta: 
          <% if @question.question_type == 2 %>
            radio button
          <% else %>
            check box
          <% end %>
        </small>

        <% unless @question_choices.any? %>
          <h6 class="mt-4">Non sono ancora presenti risposte per questa domanda.</h6>
        <% end %>

        <ol class="list-group list-group-flush mt-4">
          <% @question_choices.each.with_index(1) do |choice,index| %>
            <li class="list-group-item">
              <div class="d-flex justify-content-between align-items-center">
                <%= "#{index}. #{choice.choice}" %>
                <div>
                  <%= link_to edit_survey_question_question_choice_path(@survey, @question, choice), class: "text-decoration-none text-body" do %>
                    <svg class="bi" fill="currentColor", width="1em", height="1em">
                      <use xlink:href="<%= asset_path "bootstrap-icons/bootstrap-icons.svg" %>#tools"/>
                    </svg>
                  <% end %>
                  <%= link_to survey_question_question_choice_path(@survey.id, @question.id, choice.id),
                              method: :delete,
                              class: "text-decoration-none text-danger", 
                              data: { confirm: "Confermi di voler eliminare questa risposta?" } do %>
                    <svg class="bi" fill="currentColor", width="1em", height="1em">
                      <use xlink:href="<%= asset_path "bootstrap-icons/bootstrap-icons.svg" %>#trash"/>
                    </svg>
                  <% end %>
                </div>
              </div>
            </li>
          <% end %>
        </ol>

        <%= link_to "+ Aggiungi una risposta", new_survey_question_question_choice_path(@survey, @question), class: "btn btn-outline-primary btn-block mt-4" %>

      </div>
    </div>
  </div>
</div>

app/views/question_choices/new.html.erb
<%= render 'shared/header_survey' %>
<small class="mb-3"> <%= link_to "← Torna indietro", survey_path(@survey) %> </small>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <div class="card-text">

        <h5 class="mb-4">Aggiungi una risposta</h5>

        <%= form_with model: @question_choice, url: survey_question_question_choices_path(@survey, @question), remote: true do |f| %>
          <div class="form-group px-3">
            <%= f.text_field :choice, class: "form-control", required: true, 
                data: { autocomplete_choice: question_choice_suggested } %>
          </div>
          <%= f.submit "Aggiungi", class:"btn btn-primary mt-3" %>
        <% end %>

      </div>
    </div>
  </div>
</div>