config/routes.rb
Rails.application.routes.draw do
  root 'surveys#index'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :creators, only: [:new, :create, :show, :edit, :update]

  resources :surveys do

    get 'statistic', on: :member

    resources :answers, only: [:new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :questions, only: [:new, :create, :edit, :update, :destroy] do
      resources :question_choices, only: [:index, :new, :create, :edit, :update, :destroy]
    end

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_many :surveys, dependent: :destroy
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save { self.email = email.downcase }

  validates :email, 
        presence: true, 
        length: { maximum: 255 }, 
        format: { with: VALID_EMAIL_REGEX }, 
        uniqueness: { case_sensitive: false } 

  validates :name, 
        presence: true, 
        length: { maximum: 50 }

  validates :surname, 
        presence: true, 
        length: { maximum: 50 }

  has_secure_password
  validates :password, 
        length: { minimum: 6 },
        allow_blank: true


  # Returns the hash digest of the given string.
  def Creator.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  before_action :logged_in_creator, only: [:show, :edit, :update]
  before_action :correct_creator, only: [:show, :edit, :update]

  def new
    @creator = Creator.new
  end

  def create
    @creator = Creator.new(creator_params)
    if @creator.save
      log_in @creator
      flash[:success] = "Benvenuto nella Survey app"
      redirect_to @creator
    else
      flash[:danger] = @creator.errors.full_messages[0]
      redirect_to new_creator_path
    end
  end

  def show
    @creator = Creator.find(params[:id])
  end

  def edit
    @creator = Creator.find(params[:id])
  end

  def update
    @creator = Creator.find(params[:id])
    if @creator.update(creator_params)
      flash[:success] = "Modifica effettuata con successo!"
    else
      flash[:danger] = "Qualcosa è andato storto :/"
    end
    redirect_to @creator
  end

  private

  def creator_params
    params.require(:creator).permit(:name, :surname, :email, :password, :password_confirmation)
  end

  def correct_creator
    @creator = Creator.find(params[:id])
    redirect_to(root_url) unless current_creator?(@creator)
  end
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/views/creators/edit.html.erb
<h1 class="mb-0"><%= @creator.email %></h1>
<div class="mb-3">
  <small><%= link_to "← Torna al profilo", creator_path(@creator) %></small>
</div>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <div class="card-text">

        <h5 class="mb-4">Impostazioni</h5>

        <%= form_with model: @creator, url: creator_path(@creator) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <div class="form-group">
            <%= f.label :name, "Nome" %>
            <%= f.text_field :name, class: "form-control", required: true %>
          </div>
          <div class="form-group">
            <%= f.label :surname, "Cognome" %>
            <%= f.text_field :surname, class: "form-control", required: true %>
          </div>
          <div class="form-group">
            <%= f.label :email, "Email" %>
            <%= f.text_field :email, class: "form-control", required: true %>
          </div>

          <hr class="my-4"/>
          
          <div class="form-group">
            <%= f.label :password, "Nuova password" %>
            <%= f.password_field :password, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, "Conferma nuova password" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>

          <%= f.submit "Aggiorna", class: "btn btn-primary mt-3" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/creators/new.html.erb
<h1 class="mb-0">Registrazione</h1>
<div class="mb-3">
  <small><%= link_to "← Torna ai sondaggi", root_url %></small>
</div>

<div class="row">
  <div class="col-10">
    <%= form_with model: @creator do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "Nome", class: 'mt-4' %>
      <%= f.text_field :name, class: 'form-control', required: true %>

      <%= f.label :surname, "Cognome", class: 'mt-4' %>
      <%= f.text_field :surname, class: 'form-control', required: true %>

      <%= f.label :email, "Email", class: 'mt-4' %>
      <%= f.email_field :email, class: 'form-control', required: true %>

      <hr class="my-4"/>

      <%= f.label :password, "Password", class: 'mt-2' %>
      <%= f.password_field :password, class: 'form-control', required: true %>

      <%= f.label :password_confirmation, "Conferma password", class: 'mt-2' %>
      <%= f.password_field :password_confirmation, class: 'form-control', required: true %>

      <%= f.submit "Registrati", class: "btn btn-primary mt-4", required: true %>
    
    <% end %>
  </div>
</div>

app/views/creators/show.html.erb
<h1 class="mb-0"><%= @creator.email %></h1>
<div class="mb-3">
  <small><%= link_to "Logout", logout_path, method: :delete %></small>
</div>

<p>
  Benvenuto nella sezione dedicata ai creatori. Grazie ai privilegi di creatore
  hai la possibilità di creare e modificare i sondaggi, visualizzare le
  statistiche di questi ed eventualmente di modificare le tue informazioni personali.
  <br>
  Per accedere ad una di queste funzionalità, seleziona una delle voci qui sotto:
</p>

<ul class="list-group">
  <%= link_to "Sondaggi", root_path, class:"list-group-item border-0 px-0 text-reset" %>
  <%= link_to "Impostazioni", edit_creator_path(@creator), class:"list-group-item border-0 px-0 text-reset" %>
</ul>