config/routes.rb
Rails.application.routes.draw do
  root 'surveys#index'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :creators, only: [:new, :create, :show, :edit, :update]

  resources :surveys do

    get 'statistic', on: :member

    resources :answers, only: [:new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :questions, only: [:new, :create, :edit, :update, :destroy] do
      resources :question_choices, only: [:index, :new, :create, :edit, :update, :destroy]
    end

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :question_surveys
  has_many :questions, through: :question_surveys, dependent: :destroy
  has_many :survey_categories
  has_many :categories, through: :survey_categories, dependent: :destroy
  belongs_to :creator

  validates :title, 
    presence: true, 
    length: { maximum: 255 }

  validates :description, 
    presence: true, 
    length: { maximum: 65536 }
  
  validates :public,
    inclusion: { in: [true, false] }
  
  default_scope -> { order(created_at: :desc) }

  def self.search_logged(search,creator)
    if search
      search_formatted = search.downcase.parameterize
      category = Category.joins(:surveys).where("creator_id = ?", creator.id).find_by(name: search_formatted)
      surveys = category.surveys unless category.nil?
      if surveys
        return surveys
      else
        surveys = creator.surveys
      end
    else
      surveys = creator.surveys
    end
  end

  def self.search(search)
    if search
      search_formatted = search.downcase.parameterize
      category = Category.joins(:surveys).where("surveys.public = ?", "True").find_by(name: search_formatted)
      surveys = category.surveys unless category.nil?
      if surveys
        return surveys
      else
        surveys = Survey.all
      end
    else
      surveys = Survey.all
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  require 'will_paginate/array'
  before_action :logged_in_creator, only: [:new, :create, :edit, :update, :destroy, :statistic]
  before_action :correct_creator, only: [:show, :edit, :update, :destroy, :statistic]

  def index 
    if params[:search].present?
      logged_in? ? @surveys = Survey.search_logged(params[:search],current_creator) : @surveys = Survey.search(params[:search])
    else
      if logged_in?
        @surveys = current_creator.surveys.paginate(page: params[:page], per_page: 15)
      else
        @surveys = Survey.where(public: true).paginate(page: params[:page], per_page: 15)
      end
    end
  end

  def show 
    @survey = Survey.find(params[:id])
  end

  def new
    @survey = current_creator.surveys.new
  end

  def create
    @survey = current_creator.surveys.new(survey_params)
    if @survey.save
      flash[:success] = "Nuovo sondaggio creato con successo!"
      redirect_to @survey
    else
      flash[:danger] = "Qualcosa è andato storto :/"
      redirect_to root_path 
    end
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update(survey_params)
      flash[:success] = "Modifica effettuata con successo!"
    else
      flash[:danger] = @survey.errors.full_messages[0]
    end
    redirect_to @survey
  end

  def destroy
    @survey = Survey.find(params[:id])
    if @survey.destroy
      flash[:success] = "Sondaggio eliminato con successo!"
      redirect_to root_path
    else
      flash[:danger] = "Qualcosa è andato storto :/"
      redirect_to @survey
    end
  end

  def statistic
    @survey = Survey.find(params[:id])
    @questions = @survey.questions

    radio_text_question = Question.question_radio_or_text_of_survey(@survey.id)
    @number_of_answers = Answer.count_answers_of_survey(radio_text_question.first.id)
  end

  private

  def survey_params
    params.require(:survey).permit(:title, :description, :search, :public)
  end

  def correct_creator
    if logged_in?
      redirect_to(root_url) if current_creator != Survey.find(params[:id]).creator
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def percentage_choice(survey_id, question_choice_id, number_of_answers)
    number_of_answers_per_question_choice = Answer.count_answers_of_question_choice(survey_id, question_choice_id)
    if number_of_answers != 0
      percentage = (number_of_answers_per_question_choice / number_of_answers.to_f) * 100
    else
      percentage = 0
    end
  end

  def answers_text_field(survey_id, question_choice_id)
    answers = Answer.answers_of_text_field(survey_id, question_choice_id)    
  end

  def navigation_link_back(survey)
    if !(current_page?(root_path) or current_page?(surveys_path))
      tag.div class: "mb-3" do
        tag.small { link_to "← Torna indietro", :back }
      end
    end
  end

  def public_or_private
    @survey.public ? "Pubblico" : "Privato"
  end

  def surveys_suggested
    if logged_in? 
      Category.joins(:surveys).where("creator_id = ?", current_creator.id).order(:name).map(&:name)
    else
      Category.joins(:surveys).where("surveys.public = ?", "True").map(&:name)
    end
  end
end

app/views/surveys/_category.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h6>
    <span class="text-muted"> categorie: </span>
  </h6>
  <% if logged_in? %>
    <small><%= link_to "gestisci categorie", survey_categories_path(survey), class: "text-decoration-none" %></small>
  <% end %>
</div>
<h6>
  <% if survey.categories.any? %>
    <% survey.categories.each do |tag| %>
        <span class="badge badge-secondary"> <%= tag.name %> </span>
    <% end %>
  <% end %>
</h6>

app/views/surveys/_details_table.html.erb
<table class="table table-bordered table-sm">
  <thead>
    <tr>
      <th scope="col">Risposta</th>
      <th scope="col">Percentuale</th>
    </tr>
  </thead>
  <tbody>
    <% question.question_choices.each do |choice| %>
      <tr>
        <td> <%= choice.choice %> </td>
        <td> <%= percentage_choice(@survey.id, choice.id, @number_of_answers).round(2) %> % </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/surveys/_details_text_field.html.erb
<div class="d-flex justify-content-between m-3">
  <div>
    <span class="h5 align-middle"> <%= question.question %> </span>
    <% if question.profile_question %>
      <svg class="bi text-success mx-2" fill="currentColor", width="1em", height="1em">
        <use xlink:href="<%= asset_path "bootstrap-icons/bootstrap-icons.svg" %>#person-bounding-box"/>
      </svg>
    <% end %>
  </div>
  <button type="button" class="btn btn-sm btn-secondary" data-toggle="modal" data-target="#question<%=question.id%>">
    Guarda elenco risposte
  </button>
</div>
<div class="dropdown-divider"></div>

<!-- modal bootstrap -->

<div class="modal fade" id="question<%=question.id%>" tabindex="-1" aria-labelledby="questionLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="questionLabel"> <%= question.question %> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ol class="list-group list-group-flush">
          <% answers_text_field(@survey.id, question.question_choices.first.id).each do |answer| %>
            <li class="list-group-item">
              <span> <%= answer.answer %> </span>
            </li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/surveys/_question.html.erb
<li class="list-group-item"> 
  <div class="d-flex justify-content-between align-items-center">
    <div>
      <%= "#{index}. #{question.question}" %>
      <% if question.profile_question %>
        <svg class="bi text-success mx-2" fill="currentColor", width="1em", height="1em">
          <use xlink:href="<%= asset_path "bootstrap-icons/bootstrap-icons.svg" %>#person-bounding-box"/>
        </svg>
      <% end %>
    </div>
                      
    <% if logged_in? %>
      <div>
        <small>
          <%= link_to_if question.question_type != 1, 
                          "risposte disponibili",
                          survey_question_question_choices_path(@survey, question),
                          class: "text-decoration-none text-muted" %>
        </small>
        <%= link_to edit_survey_question_path(@survey, question), class: "text-decoration-none text-body" do %>
          <svg class="bi" fill="currentColor", width="1em", height="1em">
            <use xlink:href="<%= asset_path "bootstrap-icons/bootstrap-icons.svg" %>#tools"/>
          </svg>
        <% end %>
        <%= link_to survey_question_path(@survey.id, question.id),
                    method: :delete,
                    class: "text-decoration-none text-danger", 
                    data: { confirm: "Sei sicuro di voler eliminare questa domanda?" } do %>
          <svg class="bi" fill="currentColor", width="1em", height="1em">
            <use xlink:href="<%= asset_path "bootstrap-icons/bootstrap-icons.svg" %>#trash"/>
          </svg>
        <% end %>
      </div>
    <% end %>
  </div>
</li>

app/views/surveys/_survey.html.erb
<%= link_to survey_path(survey.id), 
            class:"list-group-item list-group-item-action", 
            id:"survey-"+survey.id.to_s, 
            style:"background-color: #F6F7F8;" do %>

  <div class="d-flex w-100 justify-content-between">
    <h4 class="mb-1 text-dark"><%= survey.title %></h4>
    <small><%= time_ago_in_words(survey.created_at) %></small>
  </div>
  <p class="mb-1"><%= survey.description %></p>
  
<% end %>

app/views/surveys/edit.html.erb
<%= render 'shared/header_survey' %>
<small class="mb-3"> <%= link_to "← Torna indietro", survey_path(@survey) %> </small>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <div class="card-text">

        <h5>Modifica il sondaggio</h5>

        <%= form_with model: @survey, url: survey_path(@survey) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <div class="form-group">
            <%= f.label :title, "Titolo" %>
            <%= f.text_field :title, class: "form-control", required: true %>
          </div>
          <div class="form-group">
            <%= f.label :description, "Descrizione" %>
            <%= f.text_area :description, class: "form-control", required: true %>
          </div>
          <div class="form-group">
            <%= f.label :public, "Sondaggio privato" %>
            <%= f.check_box :public, { class: "align-middle", checked: false }, "false", "true" %>
          </div>
          
          <%= f.submit "Modifica", class:"btn btn-primary mt-3" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/surveys/index.html.erb
<%= render 'shared/header_survey' %>

<div class="container px-0">
  <%= form_with url: root_path, method: "get", local: true, class: "form-inline my-3" do |f| %>
    <div class="form-group">
      <%= f.label :search, "Cerca per categoria: ", class: "mr-2" %>
      <%= f.text_field :search, class: "form-control", data: { autocomplete_category_home: surveys_suggested } %>
      <%= f.submit "Cerca", name: nil, class:"btn btn-primary ml-1" %>
    </div>
  <% end %>
</div>
<% unless params[:search].nil? || params[:search].blank? %>
  <h6>
    <span class="badge badge-secondary"> <%= params[:search].parameterize %> </span>
  </h6>
<% end %>

<% if logged_in? %>
  <div class="container">
    <%= link_to "+ Aggiungi sondaggio", new_survey_path, class: "btn btn-sm btn-outline-primary btn-block my-4" %>
  </div>
<% end %>

<div class="list-group">
  <%= render @surveys %>
</div>

<% unless logged_in? %>
  <div class="mt-3 float-left">
    <small>Sei un creatore? <%= link_to "Accedi | Registrati", login_path %></small>
  </div>
<% end %>

<div class="mt-3 mr-3 float-right">
  <% unless params[:search].present? %>
    <%= will_paginate @surveys, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <% end %>
</div>

app/views/surveys/new.html.erb
<%= render 'shared/header_survey' %>
<small class="mb-3"> <%= link_to "← Torna ai sondaggi", root_path %> </small>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <div class="card-text">

        <h5>Crea un nuovo sondaggio</h5>

        <%= form_with model: @survey do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <div class="form-group">
            <%= f.label :title, "Titolo" %>
            <%= f.text_field :title, class: "form-control", required: true %>
          </div>
          <div class="form-group">
            <%= f.label :description, "Descrizione" %>
            <%= f.text_area :description, class: "form-control", required: true %>
          </div>
          <div class="form-group">
            <%= f.label :public, "Sondaggio privato" %>
            <%= f.check_box :public, { class: "align-middle", checked: false }, "false", "true" %>
          </div>

          <%= f.submit "Crea sondaggio", class:"btn btn-primary mt-3" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/surveys/show.html.erb
<%= render 'shared/header_survey' %>
<small class="mb-3"> <%= link_to "← Torna ai sondaggi", root_path %> </small>

<div class="d-flex justify-content-between">
  <h4 class="text-muted mb-3">
    <%= @survey.title %>
    <% if logged_in? %>
      <span class="align-middle text-monospace h5">#Cod:<%= @survey.id %></span>
    <% end %>
  </h4>
  <% if logged_in? %>
    <div class="mb-1 float-right">
      <small> <%= link_to "modifica", edit_survey_path(@survey), class: "text-decoration-none" %> </small>
      <small> <%= link_to "elimina", survey_path(@survey.id), method: :delete, class: "text-decoration-none text-danger", data: { confirm: "Sei sicuro di voler eliminare il sondaggio?" } %> </small>
    </div>
  <% end %>
</div>

<% if logged_in? %>
  <div class="h8"> 
    Sondaggio <u><%= public_or_private %></u>. Condividi con l'URL: <u><%= request.original_url %></u>
  </div>
<% end %>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <div class="card-text">
        
        <% if @survey.questions.any? %>
          
          <div class="d-flex justify-content-between">
            <h5 class="mb-3">Anteprima questionario</h5>
            <% if logged_in? %>
              <div class="mb-1 float-right">
                <small> <%= link_to "statistiche", statistic_survey_path(@survey), class: "text-decoration-none" %> </small>
              </div>
            <% end %>
          </div>
          
          <%= render partial: "category", locals: { survey: @survey } %> 

          <ol class="list-group list-group-flush">
            <% @survey.questions.each.with_index(1) do |question, index| %>
              <%= render partial: "question", locals: { question: question, index: index } %>
            <% end %>
          </ol>
        <% else %>
          <h6>Non sono ancora stati inserite domande in questo sondaggio.</h6>
        <% end %>

      </div>
      
      <div class="container">
        <% if @survey.questions.any? && !logged_in? %> 
          <%= link_to "Compila", new_survey_answer_path(@survey), class: "btn btn-outline-primary btn-block mt-4" %>
        <% end %>
        <% if logged_in? %>
          <%= link_to "+ Aggiungi una domanda", new_survey_question_path(@survey), class: "btn btn-outline-primary btn-block mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/surveys/statistic.html.erb
<%= render 'shared/header_survey' %>
<small class="mb-3"> <%= link_to "← Torna indietro", survey_path(@survey) %> </small>

<div class="d-flex justify-content-between">
  <h4 class="text-muted mb-3">
    <%= @survey.title %>
    <span class="align-middle text-monospace h5">#Cod:<%= @survey.id %></span>
  </h4>
  <div class="mb-1 float-right">
    <small class="align-middle text-monospace">Risposte totali: <b><%= @number_of_answers %></b></small>
  </div>
</div>

<ol class="list-group list-group-flush">
  <% @questions.each do |question| %>
    <% if question.question_type != 1 %>
      <li class="list-group-item">
        <div class="d-flex align-items-baseline">
          <h5> <%= question.question %> </h5>
          <% if question.profile_question %>
            <svg class="bi text-success mx-2" fill="currentColor", width="1em", height="1em">
              <use xlink:href="<%= asset_path "bootstrap-icons/bootstrap-icons.svg" %>#person-bounding-box"/>
            </svg>
          <% end %>
        </div>
        <%= render partial: 'details_table', locals: { question: question } %>
      </li>
    <% else %>
      <%= render partial: 'details_text_field', locals: { question: question } %>
    <% end %>
  <% end %>
</ol>