config/routes.rb
Rails.application.routes.draw do
  root 'surveys#index'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :creators, only: [:new, :create, :show, :edit, :update]

  resources :surveys do

    get 'statistic', on: :member

    resources :answers, only: [:new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :questions, only: [:new, :create, :edit, :update, :destroy] do
      resources :question_choices, only: [:index, :new, :create, :edit, :update, :destroy]
    end

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :survey_categories
  has_many :surveys, through: :survey_categories, dependent: :destroy

  before_save do
    self.name = name.downcase
    self.name = name.parameterize
  end

  validates :name, presence: true, length: { maximum: 20 }, uniqueness: { case_sensitive: false }

  def self.find_or_create(params)
    name = params[:name].downcase.parameterize
    category = Category.find_by(name: name)
    if category.blank?
      # create a new record
      category = Category.new(name: name)
    else
      # return the record
      return category
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_creator, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :get_survey, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :correct_creator, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    @categories = @survey.categories
  end

  def new
    @category = @survey.categories.build
  end

  def create
    @category = Category.find_or_create(category_params)
    
    if @category.new_record?
      unless @category.save
        flash[:danger] = "Qualcosa è andato storto :/"
      end
    end

    @category.surveys << Survey.find(params[:survey_id])
    redirect_to survey_categories_path(@survey)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    unless @category.update(category_params)
      flash[:danger] = "Qualcosa è andato storto :/"
    end
    redirect_to survey_categories_path(@survey)
  end

  def destroy
    @category = Category.find(params[:id])
    unless @category.surveys.destroy(@survey)
      flash[:danger] = "Qualcosa è andato storto :/"
    end
    redirect_to survey_categories_path(@survey)
  end

  private 

  def category_params 
    params.require(:category).permit(:name)
  end

  def get_survey
    @survey = Survey.find(params[:survey_id])
  end

  def correct_creator
    redirect_to(root_url) if current_creator != Survey.find(@survey.id).creator
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories_suggested
    Category.order(:name).joins(:surveys).where("creator_id = ?", current_creator.id).map(&:name)
  end
end

app/views/categories/edit.html.erb
<%= render 'shared/header_survey' %>
<small class="mb-3"> <%= link_to "← Torna indietro", survey_path(@survey) %> </small>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <div class="card-text">

        <h5 class="mb-4">Modifica la categoria</h5>

        <%= form_with model: @category, url: survey_category_path(@survey, @category) do |f| %>
          <div class="form-group px-3">
            <%= f.text_field :name, class: "form-control", required: true %>
          </div>
          <%= f.submit "Modifica", class:"btn btn-primary mt-3", 
                        data: { confirm: "Confermi di voler modificare questa categoria? Tutte le categorie con questo nome da te create verranno modificate." } %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<%= render 'shared/header_survey' %>
<small class="mb-3"> <%= link_to "← Torna indietro", survey_path(@survey) %> </small>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <div class="card-text">

        <h5 class="mb-0">Gestisci categorie</h5>

         <% unless @categories.any? %>
          <h6 class="mt-4">Non sono ancora presenti categorie associate al sondaggio.</h6>
        <% end %>

        <ol class="list-group list-group-flush mt-4">
          <% @categories.each.with_index(1) do |tag,index| %>
            <li class="list-group-item">
              <div class="d-flex justify-content-between align-items-center">
                <span class="badge badge-secondary"><%= tag.name %></span>
                <div>
                  <%= link_to edit_survey_category_path(@survey, tag), class: "text-decoration-none text-body" do %>
                    <svg class="bi" fill="currentColor", width="1em", height="1em">
                      <use xlink:href="<%= asset_path "bootstrap-icons/bootstrap-icons.svg" %>#tools"/>
                    </svg>
                  <% end %>
                  <%= link_to survey_category_path(@survey.id, tag.id),
                              method: :delete,
                              class: "text-decoration-none text-danger", 
                              data: { confirm: "Confermi di voler eliminare questa categoria?" } do %>
                    <svg class="bi" fill="currentColor", width="1em", height="1em">
                      <use xlink:href="<%= asset_path "bootstrap-icons/bootstrap-icons.svg" %>#trash"/>
                    </svg>
                  <% end %>
                </div>
              </div>
            </li>
          <% end %>
        </ol>

        <%= link_to "+ Aggiungi una categoria", new_survey_category_path(@survey), class: "btn btn-outline-primary btn-block mt-4" %>
      
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'shared/header_survey' %>
<small class="mb-3"> <%= link_to "← Torna indietro", survey_path(@survey) %> </small>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <div class="card-text">

        <h5 class="mb-4">Aggiungi categorie</h5>

        <%= form_with model: @category, remote: true, url: survey_categories_path(@survey) do |f| %>
          <div class="form-group px-3">
            <%= f.text_field :name, class: "form-control", required: true, 
                data: { autocomplete_category: categories_suggested } %>
          </div>
          <%= f.submit "Aggiungi", class:"btn btn-primary mt-3" %>
        <% end %>

      </div>
    </div>
  </div>
</div>